apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: prometheus-operator
  namespace: default
  annotations:
    fluxcd.io/automated: "true"
spec:
  releaseName: prometheus-operator
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com
    name: stable/prometheus-operator
    version: latest
    ref: master
  #values:
